# Generated by Django 5.2.7 on 2025-10-19 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("cause", models.CharField(blank=True, max_length=150, null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("treatment", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("species", models.CharField(blank=True, max_length=150, null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("control_method", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiseaseCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxonomy.crop"
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taxonomy.disease",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease ↔ Crop Link",
                "verbose_name_plural": "Disease ↔ Crop Links",
                "unique_together": {("disease", "crop")},
            },
        ),
        migrations.AddField(
            model_name="disease",
            name="crops",
            field=models.ManyToManyField(
                related_name="diseases",
                through="taxonomy.DiseaseCrop",
                to="taxonomy.crop",
            ),
        ),
        migrations.CreateModel(
            name="PestCrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxonomy.crop"
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="taxonomy.pest"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pest ↔ Crop Link",
                "verbose_name_plural": "Pest ↔ Crop Links",
                "unique_together": {("pest", "crop")},
            },
        ),
        migrations.AddField(
            model_name="pest",
            name="crops",
            field=models.ManyToManyField(
                related_name="pests", through="taxonomy.PestCrop", to="taxonomy.crop"
            ),
        ),
    ]
