# Generated by Django 5.2.7 on 2025-10-19 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diseasecrop",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pestcrop",
            options={},
        ),
        migrations.RenameField(
            model_name="pest",
            old_name="control_method",
            new_name="description",
        ),
        migrations.AlterUniqueTogether(
            name="diseasecrop",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="pestcrop",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="disease",
            name="crops",
        ),
        migrations.RemoveField(
            model_name="disease",
            name="treatment",
        ),
        migrations.RemoveField(
            model_name="pest",
            name="crops",
        ),
        migrations.RemoveField(
            model_name="pest",
            name="species",
        ),
        migrations.RemoveField(
            model_name="pest",
            name="symptoms",
        ),
        migrations.AddField(
            model_name="pest",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="cause",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="diseasecrop",
            name="crop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disease_links",
                to="taxonomy.crop",
            ),
        ),
        migrations.AlterField(
            model_name="diseasecrop",
            name="disease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_links",
                to="taxonomy.disease",
            ),
        ),
        migrations.AlterField(
            model_name="pestcrop",
            name="crop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pest_links",
                to="taxonomy.crop",
            ),
        ),
        migrations.AlterField(
            model_name="pestcrop",
            name="pest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_links",
                to="taxonomy.pest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="diseasecrop",
            unique_together={("crop", "disease")},
        ),
        migrations.AlterUniqueTogether(
            name="pestcrop",
            unique_together={("crop", "pest")},
        ),
    ]
