# Generated by Django 5.2.7 on 2025-10-19 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("scientific_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("symptoms", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("scientific_name", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("symptoms", models.TextField(blank=True)),
                ("treatment", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="diagnostic_images/")),
                ("gps_location", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnostic_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="farms.plantinstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence_score", models.FloatField(default=0.0)),
                ("raw_diagnostic_output", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_urgent", models.BooleanField(default=False)),
                (
                    "diagnostic_image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="diagnostics.diagnosticimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiseaseDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "diagnosis_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diagnostics.diagnosisresult",
                    ),
                ),
                (
                    "disease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diagnostics.disease",
                    ),
                ),
            ],
            options={
                "unique_together": {("diagnosis_result", "disease")},
            },
        ),
        migrations.CreateModel(
            name="PestDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "diagnosis_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diagnostics.diagnosisresult",
                    ),
                ),
                (
                    "pest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diagnostics.pest",
                    ),
                ),
            ],
            options={
                "unique_together": {("diagnosis_result", "pest")},
            },
        ),
    ]
