# Generated by Django 5.2.7 on 2025-10-20 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diagnostics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pestdiagnosis",
            options={
                "ordering": ["-id"],
                "verbose_name": "Pest Diagnosis",
                "verbose_name_plural": "Pest Diagnoses",
            },
        ),
        migrations.AddField(
            model_name="pestdiagnosis",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pestdiagnosis",
            name="confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_diagnoses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pestdiagnosis",
            name="is_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
